[server]
    addr = "0.0.0.0"
    port = 8778

[postgres]
    account  = "postgres"
    password = "csq2400306"
    addr = "localhost"
    database = "postgres"

[rpc]
    tendermint = "https://prod-mainnet.prod.findora.org:26657/"
    platform = "https://prod-mainnet.prod.findora.org:8667/"
    platform_server = "https://prod-mainnet.prod.findora.org:8668/"
