[server]
    addr = "0.0.0.0"
    port = 8778

[postgres]
    account  = "postgres"
    password = "123456"
    addr = "localhost"
    database = "test"

[rpc]
    tendermint = "https://prod-forge.prod.findora.org:26657/"
    platform = "https://prod-forge.prod.findora.org:8667/"


