name: Check

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2

    - name: Install minimal with clippy and rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy 
        override: true

    - name: Using cache to speed up
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-stable-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check Formatting
      run: cargo fmt --all -- --check 

    - name: Check Clippy Lints 
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run Tests 
      run: cargo test --all --all-features --no-fail-fast
